const { ethers } = require('ethers');
import abi from "./abi.json"

const provider = new ethers.providers.JsonRpcProvider('http://localhost:8545');

// Set up the wallet (private key) for sending transactions (Replace with your wallet private key)
const privateKey = 'YOUR_PRIVATE_KEY';
const wallet = new ethers.Wallet(privateKey, provider);

// ABI of your contract (Add the ABI generated by Hardhat or Remix for the contract)
const contractABI = abi;

// Address of your deployed contract (Replace with your deployed contract address)
const contractAddress = '0x5FbDB2315678afecb367f032d93F642f64180aa3';

// Create a contract instance
const abuseReportContract = new ethers.Contract(contractAddress, contractABI, wallet);

// Example function to submit a report to the contract
async function submitReport() {
    // Define the reportInput data as a tuple (corresponding to your Solidity struct)
    const reportInput = [];

    try {
        // Call the submitReport function from the contract
        const tx = await abuseReportContract.submitReport(reportInput);
        console.log('Transaction submitted:', tx.hash);

        // Wait for the transaction to be mined
        const receipt = await tx.wait();
        console.log('Transaction confirmed:', receipt);
    } catch (error) {
        console.error('Error submitting report:', error);
    }
}

// Call the function to submit the report
submitReport();
